# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Forkit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Forkit

  pod 'AFNetworking', '~> 3.1'
  pod 'SDWebImage', '~> 3.8'
  
end
